name: Build Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        platform:
          - 'linux-x64'
          - 'linux-arm64v8'
        include:
          - os: macos-12
            platform: 'darwin-x64'
          - os: macos-12
            platform: 'darwin-arm64v8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pip3 install meson ninja packaging
          brew install automake nasm
      - name: Install dependencies (Linux arm64v8)
        if: matrix.platform == 'linux-arm64v8'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu qemu-user-static binfmt-support
      - name: Build ${{ matrix.platform }}
        id: build-release
        env:
          VERSION_LATEST_REQUIRED: false
        run: ./build.sh $(cat LIBVIPS_VERSION) ${{ matrix.platform }}
      - name: Generate integrity checksums
        id: integrity
        run: ./integrity.sh
      - name: Upload Release Asset (.tar.gz)
        uses: actions/upload-artifact@v4
        with:
          name: libvips-${{ matrix.platform }}
          path: libvips-*-${{ matrix.platform }}.tar.gz
      - name: Upload Release Asset (.integrity)
        uses: actions/upload-artifact@v4
        with:
          name: libvips-${{ matrix.platform }}.integrity
          path: "*.integrity"
